# Sources:
# https://github.com/replicatedhq/outdated/blob/master/.github/workflows/release.yml
# https://github.com/goreleaser/goreleaser-action/blob/v1.0.2/.github/workflows/release.yml
# https://github.com/marketplace/actions/goreleaser-action

name: release

on:
  push:
    tags: ["*"]


jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/actions/checkout/releases
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # https://github.com/actions/setup-go/releases
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      # https://github.com/goreleaser/goreleaser-action/releases
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/rajatjindal/krew-release-bot/releases
      # https://github.com/rajatjindal/kubectl-evict-pod/blob/v0.0.9/.krew.yaml
      # https://github.com/corneliusweig/ketall/blob/v1.3.2/hack/get-all.yaml
      # https://github.com/corneliusweig/ketall/blob/v1.3.2/.github/workflows/ci.yml#L84
#      -
#        # https://github.com/actions/setup-go/releases
#        name: Set up Go
#        uses: actions/setup-go@v1
#      -
#        # https://github.com/goreleaser/goreleaser-action/releases
#        name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v1
#        with:
#          # https://github.com/goreleaser/goreleaser/releases
#          version: latest
#          args: release --rm-dist
#          # https://goreleaser.com/customization/#Signing
#          key: ${{ secrets.YOUR_PRIVATE_KEY }}
#          signs:
#            - artifacts: checksum
#              args: ["--batch", "-u", "<key id, fingerprint, email, ...>", "--output", "${signature}", "--detach-sign", "${artifact}"]
